<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="A_Feedback.aspx.cs" Inherits="A_Feedback" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<br />
<table align="center">
    <tr>
        <td>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="fnm" DataSourceID="SqlDataSource1">
                <Columns>
                    <asp:BoundField DataField="fnm" HeaderText="fnm" SortExpression="fnm" />
                    <asp:BoundField DataField="femail" HeaderText="femail" SortExpression="femail" />
                    <asp:BoundField DataField="fcomment" HeaderText="fcomment" SortExpression="fcomment" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="delete from Feedback where fnm=@fnm;" SelectCommand="SELECT [fnm], [femail], [fcomment] FROM [Feedback]"></asp:SqlDataSource>
        </td>
    </tr>
</table>
</asp:Content>

