<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="StudentProfile.aspx.cs" Inherits="StudentProfile" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            height: 170px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    
    <table align="center" style="border:double">
        <tr>
            <td class="auto-style1">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
                    <Columns>
                        <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                        <asp:BoundField DataField="grno" HeaderText="grno" SortExpression="grno" />
                        <asp:BoundField DataField="stnm" HeaderText="stnm" SortExpression="stnm" />
                        <asp:BoundField DataField="cnm" HeaderText="cnm" SortExpression="cnm" />
                        <asp:BoundField DataField="gender" HeaderText="gender" SortExpression="gender" />
                        <asp:BoundField DataField="dob" HeaderText="dob" SortExpression="dob" />
                        <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                        <asp:BoundField DataField="mobile" HeaderText="mobile" SortExpression="mobile" />
                        <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />
                    </Columns>
                    <FooterStyle BackColor="White" ForeColor="#000066" />
                            <HeaderStyle BackColor="#993300" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                            <RowStyle ForeColor="#000066" />
                            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#F1F1F1" />
                            <SortedAscendingHeaderStyle BackColor="#007DBB" />
                            <SortedDescendingCellStyle BackColor="#CAC9C9" />
                            <SortedDescendingHeaderStyle BackColor="#00547E" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="delete from AddStudent1 where Id=@Id;" SelectCommand="SELECT * FROM [AddStudent1]" UpdateCommand="update AddStudent1 set grno=@grno,stnm=@stnm,cnm=@cnm,gender=@gender,dob=@dob,email=@email,mobile=@mobile,address=@address where Id=@Id;">
                    <UpdateParameters>
                        <asp:ControlParameter ControlID="GridView1" Name="grno" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="stnm" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="cnm" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="gender" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="dob" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="email" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="mobile" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="address" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="Id" PropertyName="SelectedValue" />
                    </UpdateParameters>
                </asp:SqlDataSource>
            </td>
        </tr>
    </table>
                </td>
        </tr>
    </table>
</asp:Content>

