<%@ Page Title="" Language="C#" MasterPageFile="~/Teacher.master" AutoEventWireup="true" CodeFile="T_StudProfile.aspx.cs" Inherits="T_StudProfile" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
    <br />
    <div>
        <table align="center" style="border:double">
            <tr>
                <td>
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SourceStudProf" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                        <Columns>
                            <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                            <asp:BoundField DataField="grno" HeaderText="grno" SortExpression="grno" />
                            <asp:BoundField DataField="stnm" HeaderText="stnm" SortExpression="stnm" />
                            <asp:BoundField DataField="cnm" HeaderText="cnm" SortExpression="cnm" />
                            <asp:BoundField DataField="gender" HeaderText="gender" SortExpression="gender" />
                            <asp:BoundField DataField="dob" HeaderText="dob" SortExpression="dob" />
                            <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                            <asp:BoundField DataField="mobile" HeaderText="mobile" SortExpression="mobile" />
                            <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />
                        </Columns>
                    </asp:GridView>    
                    <asp:SqlDataSource ID="SourceStudProf" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [AddStudent1]" DeleteCommand="delete from AddStudent1 where Id=@Id" UpdateCommand="update AddStudent1 set grno=@grno,stnm=@stnm,cnm=@cnm,gender=@gender,dob=@dob,email=@email,mobile=@mobile,address=@address where Id=@Id;">
                        <UpdateParameters>
                            <asp:ControlParameter ControlID="GridView1" Name="stnm" PropertyName="SelectedValue" />
                            <asp:ControlParameter ControlID="GridView1" Name="Id" PropertyName="SelectedValue" />
                            <asp:ControlParameter ControlID="GridView1" Name="grno" PropertyName="SelectedValue" />
                            <asp:ControlParameter ControlID="GridView1" Name="cnm" PropertyName="SelectedValue" />
                            <asp:ControlParameter ControlID="GridView1" Name="gender" PropertyName="SelectedValue" />
                            <asp:ControlParameter ControlID="GridView1" Name="dob" PropertyName="SelectedValue" />
                            <asp:ControlParameter ControlID="GridView1" Name="email" PropertyName="SelectedValue" />
                            <asp:ControlParameter ControlID="GridView1" Name="mobile" PropertyName="SelectedValue" />
                            <asp:ControlParameter ControlID="GridView1" Name="address" PropertyName="SelectedValue" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </td>
            </tr>
        </table>
        
    </div>
</asp:Content>

