<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="TeacherProfile.aspx.cs" Inherits="TeacherProfile" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
<table align="center">
    <tr>
        <td>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="tnm" HeaderText="tnm" SortExpression="tnm" />
                    <asp:BoundField DataField="gender" HeaderText="gender" SortExpression="gender" />
                    <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                    <asp:BoundField DataField="mobile" HeaderText="mobile" SortExpression="mobile" />
                    <asp:BoundField DataField="qualification" HeaderText="qualification" SortExpression="qualification" />
                    <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />
                    <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                </Columns>
                <FooterStyle BackColor="White" ForeColor="#000066" />
                            <HeaderStyle BackColor="#993300" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                            <RowStyle ForeColor="#000066" />
                            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#F1F1F1" />
                            <SortedAscendingHeaderStyle BackColor="#007DBB" />
                            <SortedDescendingCellStyle BackColor="#CAC9C9" />
                            <SortedDescendingHeaderStyle BackColor="#00547E" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="delete from AddTeacher where Id=@Id;" SelectCommand="SELECT * FROM [AddTeacher]" UpdateCommand="update AddTeacher set tnm=@tnm,gender=@gender,email=@email,mobile=@mobile,qualification=@qualification,address=@address,city=@city where Id=@Id">
                <UpdateParameters>
                    <asp:ControlParameter ControlID="GridView1" Name="tnm" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="Id" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="gender" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="email" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="mobile" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="qualification" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="address" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="GridView1" Name="city" PropertyName="SelectedValue" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </td>
    </tr>
</table>
</asp:Content>

